version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dest-dir/
    file_exists_behavior: overwrite

hooks:
  BeforeInstall:
    - location: ./before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./validate.sh
      timeout: 300
      runas: root
